# Generated by Django 5.0.7 on 2024-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
