# Generated by Django 5.0.7 on 2024-08-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_perfilusuario_logacesso_desenho_curtida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliacoes'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='logacesso',
            options={'verbose_name_plural': 'LogsAcesso'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name_plural': 'PerfilUsuario'},
        ),
        migrations.AlterModelOptions(
            name='suporte',
            options={'verbose_name_plural': 'Suporte'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
