# Generated by Django 5.0.7 on 2024-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_nome_customuser_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(default='Nome Padrao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sobrenome',
            field=models.CharField(default='Sobrenome Padrao', max_length=100),
            preserve_default=False,
        ),
    ]
