# Generated by Django 5.0.7 on 2024-09-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_supportmessage_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suporte',
            options={},
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='status',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
