# Generated by Django 5.0.7 on 2024-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_suporte_options_remove_suporte_assunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='suporte',
            name='assunto',
            field=models.CharField(default='Sem assunto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suporte',
            name='status',
            field=models.CharField(default='Em aberto', max_length=50),
        ),
    ]
