# Generated by Django 5.0.7 on 2024-09-26 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_suporte_data_criacao_suporte_assunto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suporte',
            options={'verbose_name_plural': 'Suporte'},
        ),
        migrations.AddField(
            model_name='suporte',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em andamento', 'Em andamento'), ('fechado', 'Fechado')], default='aberto', max_length=50),
        ),
    ]
