# Generated by Django 5.0.7 on 2024-09-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='data_comentario',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='desenho',
            old_name='data_postagem',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='desenho',
            old_name='arquivo',
            new_name='imagem',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='desenho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.desenho'),
        ),
        migrations.AlterField(
            model_name='desenho',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
