# Generated by Django 5.0.7 on 2024-10-03 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenho',
            name='curtidas',
        ),
        migrations.AddField(
            model_name='desenho',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
